#' Generates the documentation for the database
#' @param conn      PostgreSQLConnection object (generated by mg::get_connection())'
#' @param file      Path to the documentation.R file
#' @param db_table  A specification of the table with schema
#' @importFrom rlang .data
#' @importFrom magrittr `%>%`
#' @export
generate_documentation <- function(conn, file, db_table) {

  # Pull documentation from the DB
  docs <- mg::get_table(conn, 'docs.documentation') %>%
    tidyr::unite('db_table', 'schema', 'table', sep = '.') %>%
    dplyr::filter(db_table == !!db_table)

  # Skip undocumented tables
  if (mg::nrow(docs) == 0) return()

  # Separate into description and params
  description <- docs %>% dplyr::filter( is.na(.data$column_name)) %>% dplyr::select("comment")                %>% dplyr::collect()
  params      <- docs %>% dplyr::filter(!is.na(.data$column_name)) %>% dplyr::select("column_name", "comment") %>% dplyr::collect()

  # Order params according to data
  t <- db_table
  params <- data.frame(column_name = mg::get_table(conn, t) %>% colnames()) %>%
    dplyr::left_join(params, by = 'column_name')

  # Get author information
  table_spec <- stringr::str_split(db_table, '\\.')[[1]]
  schema <- purrr::pluck(table_spec, 1)
  table  <- purrr::pluck(table_spec, 2)

  # Separate into description and params
  author <- DBI::dbGetQuery(conn, paste0("SELECT tableowner FROM pg_tables where tablename = '", table, "' AND schemaname = '", schema, "'"))

  # Construct the roxygen format
  line=paste('',
             db_table,
             '',
             paste('@author', author),
             paste('@name', db_table),
             ifelse(nrow(description) == 0, '', paste('@description', description)),
             ifelse(nrow(params) == 0,      '', purrr::pmap(params, ~ paste('@param', ..1, ..2)) %>%
                      purrr::reduce(purrr::partial(.f = paste, sep = "\n#' "))),
             '@docType data',
             '@keywords data',
             sep = "\n#' ") %>%
    stringr::str_replace_all('<br>', "  \n#' ")

  # Dump to documentation.R
  write(paste(line, 'NULL', sep = '\n'), file = file, append = T)
}
